certifications:
  - chipset: Nike L
    platform: TV
    version: 5.5
    signed-cert-pdf: Nike-L-TV-2020-01-15.pdf
    original-cert-date: 2020-01-15
    base-model:
    derivatives:
      - year: 2020
        legend:
          sample:
          abbreviation:
          reference:
            - XX: Size
            - Y: Change for additional hardware
            - ZZZZ: Country/Market
        models:
  - chipset: Nike-M
    platform: TV
    version: 5.5
    signed-cert-pdf: Nike-M-TV-2020-01-14.pdf
    original-cert-date: 2020-01-14
    base-model: QN65Q80TAFXZA
    derivatives:
      - year: 2020
        legend:
          sample: QN65Q70TAFXZA
          abbreviation: QNXXQ70TYZZZZ
          reference:
            - XX: Size
            - Y: Change for additional hardware
            - ZZZZ: Country/Market
        models:
          - GQXXQ70TYZZZZ
          - GQXXQ71TYZZZZ
          - GQXXQ72TYZZZZ
          - GQXXQ73TYZZZZ
          - GQXXQ74TYZZZZ
          - GQXXQ75TYZZZZ
          - GQXXQ76TYZZZZ
          - GQXXQ77TYZZZZ
          - GQXXQ78TYZZZZ
          - GQXXQ79TYZZZZ
          - GQXXQ7DTYZZZZ
          - GQXXQ80TYZZZZ
          - GQXXQ81TYZZZZ
          - GQXXQ82TYZZZZ
          - GQXXQ83TYZZZZ
          - GQXXQ84TYZZZZ
          - GQXXQ85TYZZZZ
          - GQXXQ86TYZZZZ
          - GQXXQ87TYZZZZ
          - GQXXQ88TYZZZZ
          - GQXXQ89TYZZZZ
          - GQXXQ8DTYZZZZ
          - GQXXQ8ETYZZZZ
          - GQXXQ8PTYZZZZ
          - GQXXQ8UTYZZZZ
          - GQXXQ90TYZZZZ
          - GQXXQ95TYZZZZ
          - GQXXQ900TYZZZZ
          - GQXXQ950TYZZZZ
          - GQXXQ800TYZZZZ
          - GQXXQ850TYZZZZ
          - GQXXQ700TYZZZZ
          - GQXXLS01TYZZZZ
          - GQXXLS03TYZZZZ
          - GQXXLS05TYZZZZ
          - KQXXQT80YZZZZ
          - KQXXQT70YZZZZ
          - KQXXQT90YZZZZ
          - KQXXQT95YZZZZ
          - KQXXQT950YZZZZ
          - KQXXQT900YZZZZ
          - KQXXQT800YZZZZ
          - KQXXLST01YZZZZ
          - KQXXLST03YZZZZ
          - KQXXLST05YZZZZ
          - QAXXQ70TYZZZZ
          - QAXXQ71TYZZZZ
          - QAXXQ72TYZZZZ
          - QAXXQ73TYZZZZ
          - QAXXQ74TYZZZZ
          - QAXXQ75TYZZZZ
          - QAXXQ76TYZZZZ
          - QAXXQ77TYZZZZ
          - QAXXQ78TYZZZZ
          - QAXXQ79TYZZZZ
          - QAXXQ7DTYZZZZ
          - QAXXQ80TYZZZZ
          - QAXXQ81TYZZZZ
          - QAXXQ82TYZZZZ
          - QAXXQ83TYZZZZ
          - QAXXQ84TYZZZZ
          - QAXXQ85TYZZZZ
          - QAXXQ86TYZZZZ
          - QAXXQ87TYZZZZ
          - QAXXQ88TYZZZZ
          - QAXXQ89TYZZZZ
          - QAXXQ8DTYZZZZ
          - QAXXQ8ETYZZZZ
          - QAXXQ8PTYZZZZ
          - QAXXQ8UTYZZZZ
          - QAXXQ90TYZZZZ
          - QAXXQ95TYZZZZ
          - QAXXQ900TYZZZZ
          - QAXXQ950TYZZZZ
          - QAXXQ800TYZZZZ
          - QAXXQ850TYZZZZ
          - QAXXQ700TYZZZZ
          - QAXXLS01TYZZZZ
          - QAXXLS03TYZZZZ
          - QAXXLS05TYZZZZ
          - QEXXQ70TYZZZZ
          - QEXXQ71TYZZZZ
          - QEXXQ72TYZZZZ
          - QEXXQ73TYZZZZ
          - QEXXQ74TYZZZZ
          - QEXXQ75TYZZZZ
          - QEXXQ76TYZZZZ
          - QEXXQ77TYZZZZ
          - QEXXQ78TYZZZZ
          - QEXXQ79TYZZZZ
          - QEXXQ7DTYZZZZ
          - QEXXQ80TYZZZZ
          - QEXXQ81TYZZZZ
          - QEXXQ82TYZZZZ
          - QEXXQ83TYZZZZ
          - QEXXQ84TYZZZZ
          - QEXXQ85TYZZZZ
          - QEXXQ86TYZZZZ
          - QEXXQ87TYZZZZ
          - QEXXQ88TYZZZZ
          - QEXXQ89TYZZZZ
          - QEXXQ8DTYZZZZ
          - QEXXQ8ETYZZZZ
          - QEXXQ8PTYZZZZ
          - QEXXQ8UTYZZZZ
          - QEXXQ90TYZZZZ
          - QEXXQ95TYZZZZ
          - QEXXQ900TYZZZZ
          - QEXXQ950TYZZZZ
          - QEXXQ800TYZZZZ
          - QEXXQ850TYZZZZ
          - QEXXQ700TYZZZZ
          - QEXXLS01TYZZZZ
          - QEXXLS03TYZZZZ
          - QEXXLS05TYZZZZ
          - QNXXQ70TYZZZZ
          - QNXXQ71TYZZZZ
          - QNXXQ72TYZZZZ
          - QNXXQ73TYZZZZ
          - QNXXQ74TYZZZZ
          - QNXXQ75TYZZZZ
          - QNXXQ76TYZZZZ
          - QNXXQ77TYZZZZ
          - QNXXQ78TYZZZZ
          - QNXXQ79TYZZZZ
          - QNXXQ7DTYZZZZ
          - QNXXQ80TYZZZZ
          - QNXXQ81TYZZZZ
          - QNXXQ82TYZZZZ
          - QNXXQ83TYZZZZ
          - QNXXQ84TYZZZZ
          - QNXXQ85TYZZZZ
          - QNXXQ86TYZZZZ
          - QNXXQ87TYZZZZ
          - QNXXQ88TYZZZZ
          - QNXXQ89TYZZZZ
          - QNXXQ8DTYZZZZ
          - QNXXQ8ETYZZZZ
          - QNXXQ8PTYZZZZ
          - QNXXQ8UTYZZZZ
          - QNXXQ90TYZZZZ
          - QNXXQ95TYZZZZ
          - QNXXQ900TYZZZZ
          - QNXXQ950TYZZZZ
          - QNXXQ800TYZZZZ
          - QNXXQ850TYZZZZ
          - QNXXQ700TYZZZZ
          - QNXXLS01TYZZZZ
          - QNXXLS03TYZZZZ
          - QNXXLS05TYZZZZ
          - QTV-QWJ00/T
          - QNXXLST7TYZZZZ
          - GQXXLST7TYZZZZ
          - QAXXLST7TYZZZZ
          - QNXXLST7TYZZZZ
          - QTLST7K-XX UHD D.ME0
          - LHXXBHTELGZZZZ
          - KQXXQT81YZZZZ
          - KQXXQT82YZZZZ
          - KQXXQT83YZZZZ
          - KQXXQT84YZZZZ
          - KQXXQT85YZZZZ
          - KQXXQT86YZZZZ
          - KQXXQT87YZZZZ
          - KQXXQT88YZZZZ
          - KQXXQT89YZZZZ
          - KQXXLSTT7YZZZZ
          - HGXXTS030YZZZZ
          - HGXXTQ800YZZZZ
          - QAXXQ7ATYZZZZ
          - HGXXTS010YZZZZ
  - chipset: Kant-S2
    platform: TV
    version: 5.5
    signed-cert-pdf: Kant-S2-TV-2020-01-22.pdf
    original-cert-date: 2020-01-22
    base-model: UN43T5300AFXZX
    derivatives:
      - year: 2020
        legend:
          sample: UN43T5300AFXZX
          abbreviation: HGXXT5300ZZZZZ
          reference:
            - XX: Size
            - ZZZZZ: Country/Market
        models:
          - GUXXT5379YZZZZ
          - GUXXT4309YZZZZ
          - KUXXT5300YZZZZ
          - UAXXT4300YZZZZ
          - UAXXT4400YZZZZ
          - UAXXT4500YZZZZ
          - UAXXT4550YZZZZ
          - UAXXT4700YZZZZ
          - UAXXT4750YZZZZ
          - UAXXT5300YZZZZ
          - UAXXT5400YZZZZ
          - UAXXT5500YZZZZ
          - UAXXT5700YZZZZ
          - UAXXT5770YZZZZ
          - UAXXT6000YZZZZ
          - UAXXT6500YZZZZ
          - UAXXTE50AYZZZZ
          - UAXXTE50FYZZZZ
          - UAXXTE40AYZZZZ
          - UAXXTE40FYZZZZ
          - UEXXT5300YZZZZ
          - UEXXT5302YZZZZ
          - UEXXT5305YZZZZ
          - UEXXT5370YZZZZ
          - UEXXT5372YZZZZ
          - UEXXT5375YZZZZ
          - UEXXT4300YZZZZ
          - UEXXT4302YZZZZ
          - UEXXT4305YZZZZ
          - UEXXT4500YZZZZ
          - UEXXT4510YZZZZ
          - UNXXT5300YZZZZ
          - UNXXT4300YZZZZ
          - HGXXT5300ZZZZZ
  - chipset: Kant-SU2
    platform: TV
    version: 5.5
    signed-cert-pdf: Kant-SU2-TV-2020-01-24.pdf
    original-cert-date: 2020-01-24
    base-model: UN65TU7000FXZA
    derivatives:
      - year: 2020
        legend:
          sample: QN65Q70TAFXZA
          abbreviation: QNXXQ70TYZZZZ
          reference:
            - XX: Size
            - Y: Change for additional hardware
            - ZZZZ: Country/Market
        models:
          - GQ32LS03TYZZZZ
          - GUXXTU7079ZZZZ
          - GUXXTU7179ZZZZ
          - GUXXTU7199ZZZZ
          - KUXXUT7000ZZZZ
          - QA32LS03TYZZZZ
          - QE32LS03TYZZZZ
          - QN32LS03TYZZZZ
          - UAXXTU7000ZZZZ
          - UAXXTU7200ZZZZ
          - UEXXTU7000ZZZZ
          - UEXXTU7002ZZZZ
          - UEXXTU7005ZZZZ
          - UEXXTU7010ZZZZ
          - UEXXTU7025ZZZZ
          - UEXXTU7070ZZZZ
          - UEXXTU7072ZZZZ
          - UEXXTU7075ZZZZ
          - UEXXTU7079ZZZZ
          - UEXXTU7090ZZZZ
          - UEXXTU7092ZZZZ
          - UEXXTU7095ZZZZ
          - UEXXTU7100ZZZZ
          - UEXXTU7102ZZZZ
          - UEXXTU7105ZZZZ
          - UEXXTU7110ZZZZ
          - UEXXTU7122ZZZZ
          - UEXXTU7125ZZZZ
          - UEXXTU7140ZZZZ
          - UEXXTU7160ZZZZ
          - UEXXTU7170ZZZZ
          - UEXXTU7172ZZZZ
          - UEXXTU7175ZZZZ
          - UEXXTU7190ZZZZ
          - UEXXTU7192ZZZZ
          - UEXXTU7195ZZZZ
          - UEXXTU7500ZZZZ
          - UEXXTU7540ZZZZ
          - UEXXTU7560ZZZZ
          - UEXXTU7570ZZZZ
          - UNXXTU7000ZZZZ
          - UNXXTU7050ZZZZ
          - UNXXTU7100ZZZZ
          - UNXXTU700DZZZZ
          - LSXXAM50YYZZZZ
          - LSXXAM70YYZZZZ
  - chipset: Kant-SU2 (Projector)
    platform: TV
    version: 5.5
    signed-cert-pdf: Kant-SU2-Projector-TV-2020-06-11.pdf
    original-cert-date: 2020-06-11
    base-model: SP-LSTP7AFXKR
    derivatives:
      - year: 2020
        legend:
          sample:
          abbreviation:
          reference:
            - XX: Size
            - Y: Change for additional hardware
            - ZZZZ: Country/Market
        models:
          - SP-LSP7TFAXZA
          - SP-LSP9TFAXZA
          - SP-LSP7TFAXXU
          - SP-LSP9TFAXXU
          - SP-LSP7TFAXZG
          - SP-LSP9TFAXZG
          - SP-LSP7TFAXXC
          - SP-LSP9TFAXXC
          - SP-LSTP7AFXKR
          - SP-LSTP9AFXKR
          - SP-LSP7TFAXXZ
          - SP-LSP9TFAXXZ
          - SP-LSP7TFAXXY
          - SP-LSP9TFAXXY
  - chipset: Kant-M2e
    platform: Smart Signage
    version: 4.0
    signed-cert-pdf: Kant-M2e-Smart_signage-2020-08-14.pdf
    original-cert-date: 2018-04-20
    base-model: LH49QMNEBGC
    derivatives:
      - year: 2020
        legend:
          sample:
          abbreviation:
          reference:
            - XX: Size
            - Y: Change for additional hardware
            - ZZZZ: Country/Market
        models:
          - LH13QBREBGC
          - LH13QBRTBGC
          - LH43QBNEBGC
          - LH43QBREBGC
          - LH43QHREBGC
          - LH43QMNEBGC
          - LH43QMREBGC
          - LH46OMNDPGB
          - LH46OMNSLGB
          - LH46VMRUBGB
          - LH49QBNEBGC
          - LH49QBREBGC
          - LH49QHREBGC
          - LH49QMREBGC
          - LH55OMNDPGB
          - LH55OMNSLGB
          - LH55QBNEBGC
          - LH55QBREBGC
          - LH55QBRNBGC
          - LH55QHREBGC
          - LH55QMNEBGC
          - LH55QMREBGC
          - LH65QBNEBGC
          - LH65QBREBGC
          - LH65QBRNBGC
          - LH65QHREBGC
          - LH65QMNEBGC
          - LH65QMREBGC
          - LH75QBNEBGC
          - LH75QBREBGC
          - LH75QBRNBGC
          - LH75QHREBGC
          - LH75QMNEBGC
          - LH75QMREBGC
          - LH82QENELGC
          - LH85OHNDKGB
          - LH85OHNSKGB
          - LH85QMNEBGC
          - LH98QBREBGC
          - LH98QMNEBGC
          - SBB-SNOWJAU/ZA
          - SBB-SS08NL1
          - LH50QBREBGCXEN
          - LH85QBREBGCXZA
          - LH50QMREBGCXEN
          - LH85QMREBGCXZA
          - LH50QHREBGCXEN
          - LH24KMATBGCXKR