certifications:
  - chipset: Nike L
    platform: TV
    version: 5.5
    signed-cert-pdf: Nike-L-TV-2020-01-15.pdf
    original-cert-date: 2020-01-15
    base-model:
    derivatives:
      - year: 2020
        legend:
          sample:
          abbreviation:
          reference:
            - XX: Size
            - Y: Change for additional hardware
            - ZZZZ: Country/Market
        models:
  - chipset: Nike-M
    platform: TV
    version: 5.5
    signed-cert-pdf: Nike-M-TV-2020-01-14.pdf
    original-cert-date: 2020-01-14
    base-model: QN65Q80TAFXZA
    derivatives:
      - year: 2020
        legend:
          sample: QN65Q70TAFXZA
          abbreviation: QNXXQ70TYZZZZ
          reference:
            - XX: Size
            - Y: Change for additional hardware
            - ZZZZ: Country/Market
        models:
          - GQXXQ70TYZZZZ
          - GQXXQ71TYZZZZ
          - GQXXQ72TYZZZZ
          - GQXXQ73TYZZZZ
          - GQXXQ74TYZZZZ
          - GQXXQ75TYZZZZ
          - GQXXQ76TYZZZZ
          - GQXXQ77TYZZZZ
          - GQXXQ78TYZZZZ
          - GQXXQ79TYZZZZ
          - GQXXQ7DTYZZZZ
          - GQXXQ80TYZZZZ
          - GQXXQ81TYZZZZ
          - GQXXQ82TYZZZZ
          - GQXXQ83TYZZZZ
          - GQXXQ84TYZZZZ
          - GQXXQ85TYZZZZ
          - GQXXQ86TYZZZZ
          - GQXXQ87TYZZZZ
          - GQXXQ88TYZZZZ
          - GQXXQ89TYZZZZ
          - GQXXQ8DTYZZZZ
          - GQXXQ8ETYZZZZ
          - GQXXQ8PTYZZZZ
          - GQXXQ8UTYZZZZ
          - GQXXQ90TYZZZZ
          - GQXXQ95TYZZZZ
          - GQXXQ900TYZZZZ
          - GQXXQ950TYZZZZ
          - GQXXQ800TYZZZZ
          - GQXXQ850TYZZZZ
          - GQXXQ700TYZZZZ
          - GQXXLS01TYZZZZ
          - GQXXLS03TYZZZZ
          - GQXXLS05TYZZZZ
          - KQXXQT80YZZZZ
          - KQXXQT70YZZZZ
          - KQXXQT90YZZZZ
          - KQXXQT95YZZZZ
          - KQXXQT950YZZZZ
          - KQXXQT900YZZZZ
          - KQXXQT800YZZZZ
          - KQXXLST01YZZZZ
          - KQXXLST03YZZZZ
          - KQXXLST05YZZZZ
          - QAXXQ70TYZZZZ
          - QAXXQ71TYZZZZ
          - QAXXQ72TYZZZZ
          - QAXXQ73TYZZZZ
          - QAXXQ74TYZZZZ
          - QAXXQ75TYZZZZ
          - QAXXQ76TYZZZZ
          - QAXXQ77TYZZZZ
          - QAXXQ78TYZZZZ
          - QAXXQ79TYZZZZ
          - QAXXQ7DTYZZZZ
          - QAXXQ80TYZZZZ
          - QAXXQ81TYZZZZ
          - QAXXQ82TYZZZZ
          - QAXXQ83TYZZZZ
          - QAXXQ84TYZZZZ
          - QAXXQ85TYZZZZ
          - QAXXQ86TYZZZZ
          - QAXXQ87TYZZZZ
          - QAXXQ88TYZZZZ
          - QAXXQ89TYZZZZ
          - QAXXQ8DTYZZZZ
          - QAXXQ8ETYZZZZ
          - QAXXQ8PTYZZZZ
          - QAXXQ8UTYZZZZ
          - QAXXQ90TYZZZZ
          - QAXXQ95TYZZZZ
          - QAXXQ900TYZZZZ
          - QAXXQ950TYZZZZ
          - QAXXQ800TYZZZZ
          - QAXXQ850TYZZZZ
          - QAXXQ700TYZZZZ
          - QAXXLS01TYZZZZ
          - QAXXLS03TYZZZZ
          - QAXXLS05TYZZZZ
          - QEXXQ70TYZZZZ
          - QEXXQ71TYZZZZ
          - QEXXQ72TYZZZZ
          - QEXXQ73TYZZZZ
          - QEXXQ74TYZZZZ
          - QEXXQ75TYZZZZ
          - QEXXQ76TYZZZZ
          - QEXXQ77TYZZZZ
          - QEXXQ78TYZZZZ
          - QEXXQ79TYZZZZ
          - QEXXQ7DTYZZZZ
          - QEXXQ80TYZZZZ
          - QEXXQ81TYZZZZ
          - QEXXQ82TYZZZZ
          - QEXXQ83TYZZZZ
          - QEXXQ84TYZZZZ
          - QEXXQ85TYZZZZ
          - QEXXQ86TYZZZZ
          - QEXXQ87TYZZZZ
          - QEXXQ88TYZZZZ
          - QEXXQ89TYZZZZ
          - QEXXQ8DTYZZZZ
          - QEXXQ8ETYZZZZ
          - QEXXQ8PTYZZZZ
          - QEXXQ8UTYZZZZ
          - QEXXQ90TYZZZZ
          - QEXXQ95TYZZZZ
          - QEXXQ900TYZZZZ
          - QEXXQ950TYZZZZ
          - QEXXQ800TYZZZZ
          - QEXXQ850TYZZZZ
          - QEXXQ700TYZZZZ
          - QEXXLS01TYZZZZ
          - QEXXLS03TYZZZZ
          - QEXXLS05TYZZZZ
          - QNXXQ70TYZZZZ
          - QNXXQ71TYZZZZ
          - QNXXQ72TYZZZZ
          - QNXXQ73TYZZZZ
          - QNXXQ74TYZZZZ
          - QNXXQ75TYZZZZ
          - QNXXQ76TYZZZZ
          - QNXXQ77TYZZZZ
          - QNXXQ78TYZZZZ
          - QNXXQ79TYZZZZ
          - QNXXQ7DTYZZZZ
          - QNXXQ80TYZZZZ
          - QNXXQ81TYZZZZ
          - QNXXQ82TYZZZZ
          - QNXXQ83TYZZZZ
          - QNXXQ84TYZZZZ
          - QNXXQ85TYZZZZ
          - QNXXQ86TYZZZZ
          - QNXXQ87TYZZZZ
          - QNXXQ88TYZZZZ
          - QNXXQ89TYZZZZ
          - QNXXQ8DTYZZZZ
          - QNXXQ8ETYZZZZ
          - QNXXQ8PTYZZZZ
          - QNXXQ8UTYZZZZ
          - QNXXQ90TYZZZZ
          - QNXXQ95TYZZZZ
          - QNXXQ900TYZZZZ
          - QNXXQ950TYZZZZ
          - QNXXQ800TYZZZZ
          - QNXXQ850TYZZZZ
          - QNXXQ700TYZZZZ
          - QNXXLS01TYZZZZ
          - QNXXLS03TYZZZZ
          - QNXXLS05TYZZZZ
          - QTV-QWJ00/T
          - QNXXLST7TYZZZZ
          - GQXXLST7TYZZZZ
          - QAXXLST7TYZZZZ
          - QNXXLST7TYZZZZ
          - QTLST7K-XX UHD D.ME0
          - LHXXBHTELGZZZZ
          - KQXXQT81YZZZZ
          - KQXXQT82YZZZZ
          - KQXXQT83YZZZZ
          - KQXXQT84YZZZZ
          - KQXXQT85YZZZZ
          - KQXXQT86YZZZZ
          - KQXXQT87YZZZZ
          - KQXXQT88YZZZZ
          - KQXXQT89YZZZZ
          - KQXXLSTT7YZZZZ
          - HGXXTS030YZZZZ
          - HGXXTQ800YZZZZ
          - QAXXQ7ATYZZZZ
          - HGXXTS010YZZZZ
  - chipset: Kant-S2
    platform: TV
    version: 5.5
    signed-cert-pdf: Kant-S2-TV-2020-01-22.pdf
    original-cert-date: 2020-01-22
    base-model: UN43T5300AFXZX
    derivatives:
      - year: 2020
        legend:
          sample:
          abbreviation:
          reference:
            - XX: Size
            - Y: Change for additional hardware
            - ZZZZ: Country/Market
        models:
          - UN43T5300AFXZX
          - KU43T5300AFXKR
          - GU32T5379AUXZG
          - UA40T5300AUSMM
          - UA40T5300AUSMZ
          - UA40T5300AUXEG
          - UA40T5300AUXKE
          - UA40T5300AUXLY
          - UA40T5300AUXMM
          - UA40T5300AUXMV
          - UA40T5300AUXTW
          - UA40T5300AUXUM
          - UA40T5300AUXZN
          - UA43T5300AJXZK
          - UA43T5300AUSMM
          - UA43T5300AUSMZ
          - UA43T5300AUXEG
          - UA43T5300AUXKE
          - UA43T5300AUXLY
          - UA43T5300AUXMM
          - UA43T5300AUXMV
          - UA43T5300AUXQR
          - UA43T5300AUXTW
          - UA43T5300AUXUM
          - UA43T5300AUXZN
          - UA43T5400ARSHE
          - UA43T5400ARXER
          - UA43T5400ARXFS
          - UA43T5400ARXHE
          - UA43T5400ARXSG
          - UA43T5500AKCXL
          - UA43T5500AKXXL
          - UA43T5500ARSHE
          - UA43T5500ARXFS
          - UA43T5500ARXHE
          - UA43T5500ARXSG
          - UA43T5700ARXER
          - UA43T5700ARXFS
          - UA43T5700ARXSG
          - UA43T5770AUBXL
          - UA43T5770AUCXL
          - UA43T5770AUXXL
          - UA43T6000AGXXP
          - UA43T6000AKXMR
          - UA43T6000AKXXD
          - UA43T6000AKXXM
          - UA43T6000AKXXS
          - UA43T6000AKXXT
          - UA43T6000AKXXV
          - UA43T6500AGXXP
          - UA43T6500AKXMR
          - UA43T6500AKXXD
          - UA43T6500AKXXM
          - UA43T6500AKXXS
          - UA43T6500AKXXT
          - UA43T6500AKXXV
          - UA43T6500ASXNZ
          - UA43TE50AAKCXL
          - UA43TE50AAKXXL
          - UA43TE50FAKCXL
          - UA43TE50FAKXXL
          - UE32T5300AKXXH
          - UE32T5300AKXXU
          - UE32T5300AUXCE
          - UE32T5300AUXRU
          - UE32T5300AUXUA
          - UE32T5300AWXXN
          - UE32T5302AKXXH
          - UE32T5305AKXXC
          - UE32T5370AUXXH
          - UE32T5370AUXZG
          - UE32T5370AUXZT
          - UE32T5372AUXXH
          - UE32T5375AUXXC
          - UE40T5300AUSTK
          - UE40T5300AUXSQ
          - UE40T5300AUXTK
          - UE43T5300AUXCE
          - UE43T5300AUXRU
          - UE43T5300AUXUA
          - UN43T5300AGCZD
          - UN43T5300AGXPE
          - UN43T5300AGXPR
          - UN43T5300AGXUG
          - UN43T5300AGXZB
          - UN43T5300AGXZD
          - UN43T5300AGXZS
          - UN43T5300AKXZL
          - UN43T5300APXPA
          - GU32T4309AKXZG
          - UA32T4300AGXXP
          - UA32T4300AJXZK
          - UA32T4300AKXMR
          - UA32T4300AKXXD
          - UA32T4300AKXXM
          - UA32T4300AKXXS
          - UA32T4300AKXXT
          - UA32T4300AKXXV
          - UA32T4300ASXNZ
          - UA32T4300AWXNZ
          - UA32T4400ARSFS
          - UA32T4400ARSHE
          - UA32T4400ARXER
          - UA32T4400ARXFS
          - UA32T4400ARXHE
          - UA32T4400ARXSG
          - UA32T4500AKXXL
          - UA32T4500ARSFS
          - UA32T4500ARSHE
          - UA32T4500ARXER
          - UA32T4500ARXFS
          - UA32T4500ARXHE
          - UA32T4500ARXSG
          - UA32T4550AKXXL
          - UA32T4700AKXXL
          - UA32T4700ARSFS
          - UA32T4700ARXER
          - UA32T4700ARXFS
          - UA32T4700ARXSG
          - UA32T4750AKXXL
          - UA32T5300AUSMM
          - UA32T5300AUSMZ
          - UA32T5300AUXEG
          - UA32T5300AUXGH
          - UA32T5300AUXKE
          - UA32T5300AUXLY
          - UA32T5300AUXMM
          - UA32T5300AUXMV
          - UA32T5300AUXQR
          - UA32T5300AUXTW
          - UA32T5300AUXUM
          - UA32T5300AUXZN
          - UA32TE40AAKXXL
          - UA32TE40FAKXXL
          - UE32T4300AKXXH
          - UE32T4300AKXXU
          - UE32T4300AWXXN
          - UE32T4302AKXXH
          - UE32T4305AKXXC
          - UE32T4500AUXCE
          - UE32T4500AUXRU
          - UE32T4500AUXUA
          - UE32T4510AUXCE
          - UE32T4510AUXRU
          - UE32T5300AUSTK
          - UE32T5300AUXMI
          - UE32T5300AUXSQ
          - UE32T5300AUXTK
          - UN32T4300AFXZX
          - UN32T4300AGCZD
          - UN32T4300AGXPE
          - UN32T4300AGXPR
          - UN32T4300AGXUG
          - UN32T4300AGXZB
          - UN32T4300AGXZD
          - UN32T4300AGXZS
          - UN32T4300AKXZL
          - UN32T4300APXPA
  - chipset: Kant-SU2
    platform: TV
    version: 5.5
    signed-cert-pdf: Kant-SU2-TV-2020-01-24.pdf
    original-cert-date: 2020-01-24
    base-model: UN65TU7000FXZA
    derivatives:
      - year: 2020
        legend:
          sample: QN65Q70TAFXZA
          abbreviation: QNXXQ70TYZZZZ
          reference:
            - XX: Size
            - Y: Change for additional hardware
            - ZZZZ: Country/Market
        models:
          - GQ32LS03TYZZZZ
          - GUXXTU7079ZZZZ
          - GUXXTU7179ZZZZ
          - GUXXTU7199ZZZZ
          - KUXXUT7000ZZZZ
          - QA32LS03TYZZZZ
          - QE32LS03TYZZZZ
          - QN32LS03TYZZZZ
          - UAXXTU7000ZZZZ
          - UAXXTU7200ZZZZ
          - UEXXTU7000ZZZZ
          - UEXXTU7002ZZZZ
          - UEXXTU7005ZZZZ
          - UEXXTU7010ZZZZ
          - UEXXTU7025ZZZZ
          - UEXXTU7070ZZZZ
          - UEXXTU7072ZZZZ
          - UEXXTU7075ZZZZ
          - UEXXTU7079ZZZZ
          - UEXXTU7090ZZZZ
          - UEXXTU7092ZZZZ
          - UEXXTU7095ZZZZ
          - UEXXTU7100ZZZZ
          - UEXXTU7102ZZZZ
          - UEXXTU7105ZZZZ
          - UEXXTU7110ZZZZ
          - UEXXTU7122ZZZZ
          - UEXXTU7125ZZZZ
          - UEXXTU7140ZZZZ
          - UEXXTU7160ZZZZ
          - UEXXTU7170ZZZZ
          - UEXXTU7172ZZZZ
          - UEXXTU7175ZZZZ
          - UEXXTU7190ZZZZ
          - UEXXTU7192ZZZZ
          - UEXXTU7195ZZZZ
          - UEXXTU7500ZZZZ
          - UEXXTU7540ZZZZ
          - UEXXTU7560ZZZZ
          - UEXXTU7570ZZZZ
          - UNXXTU7000ZZZZ
          - UNXXTU7050ZZZZ
          - UNXXTU7100ZZZZ
          - UNXXTU700DZZZZ
          - LSXXAM50YYZZZZ
          - LSXXAM70YYZZZZ
  - chipset: Kant-SU2 (Projector)
    platform: TV
    version: 5.5
    signed-cert-pdf: Kant-SU2-Projector-TV-2020-06-11.pdf
    original-cert-date: 2020-06-11
    base-model: SP-LSTP7AFXKR
    derivatives:
      - year: 2020
        legend:
          sample:
          abbreviation:
          reference:
            - XX: Size
            - Y: Change for additional hardware
            - ZZZZ: Country/Market
        models:
          - SP-LSP7TFAXZA
          - SP-LSP9TFAXZA
          - SP-LSP7TFAXXU
          - SP-LSP9TFAXXU
          - SP-LSP7TFAXZG
          - SP-LSP9TFAXZG
          - SP-LSP7TFAXXC
          - SP-LSP9TFAXXC
          - SP-LSTP7AFXKR
          - SP-LSTP9AFXKR
          - SP-LSP7TFAXXZ
          - SP-LSP9TFAXXZ
          - SP-LSP7TFAXXY
          - SP-LSP9TFAXXY
